from enum import Enum


class ErrorCode:
    INVALID_AUTHENTICATION_CREDENTIALS = 'INVALID_AUTHENTICATION_CREDENTIALS'
    INVALID_INPUT = "INVALID_INPUT"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PASSWORD_DOES_NOT_MATCH = "PASSWORD_DOES_NOT_MATCH"
    OLD_PASSWORD_DOES_NOT_MATCH = "OLD_PASSWORD_DOES_NOT_MATCH"


class GenderChoices(Enum):
    MALE = 'MALE'
    FEMALE = 'FEMALE'
    DEFAULT = 'DEFAULT'
